### ISSUE TITLE
VerilogCreator is incompatible with QtCreator 4.x

### ISSUE THREAD

**Issue by atq2119** [rochus-keller/VerilogCreator#1]
Attempting to build VerilogCreator against QtCreator 4.x fails with various build errors, e.g.:
```
In file included from VlEditorDocument.cpp:20:0:
VlEditorDocument.h:37:14: error: conflicting return type specified for ‘virtual bool Vl::EditorDocument1::open(QString*, const QString&, const QString&)’
         bool open(QString *errorString, const QString &fileName, const QString &realFileName);
              ^~~~
In file included from VlEditorDocument.h:23:0,
                 from VlEditorDocument.cpp:20:
../qt-creator-opensource-src-4.5.2/src/plugins/texteditor/textdocument.h:119:16: error:   overriding ‘virtual Core::IDocument::OpenResult TextEditor::TextDocument::open(QString*, const QString&, const QString&)’
     OpenResult open(QString *errorString, const QString &fileName,
                ^~~~
```

**Comment by rochus-keller** [comment]
Apparently they have changed the API in Qt Creator 4.x. I only use Qt Creator 3.x.
Seems to be easy to fix. Change the return type of Vl::EditorDocument::open and of the "res" variable in the body from bool to OpenResult. I will add an Ifdef in future versions.

**Comment by rochus-keller** [comment]
I found a feasible solution to the problem.  Instead of adapting the plugin to each major and minor QtCreator version, I offer a simple binary deployment for Linux, Windows and Mac of a lean QtCreator version including VerilogCreator and some other minimal required plugins. See here to learn more: https://github.com/rochus-keller/QtcVerilog. Comments are welcome.

**Comment by rochus-keller** [comment]
After a month and five releases von VerilogCreator together with QtcVerilog I can say that this solution has proven itself. People can immediately download and use VerilogCreator without the hassels of comiling it themselves and I don't have to spend any minute on Qt Creator API compatibility. According to my download statistics it is being used and nobody complained so far. I therefore close the issue.
